// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: acc_balance.proto

// имя proto-пакета и версия
// версию указывать необязательно, это общепринятый подход
// для версионирования спецификации

package main

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// описание типа AccountBalance
type AccountBalance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AccountIdHash []byte                 `protobuf:"bytes,1,opt,name=account_id_hash,json=accountIdHash,proto3" json:"account_id_hash,omitempty"` // Go: []byte
	IsBlocked     bool                   `protobuf:"varint,2,opt,name=is_blocked,json=isBlocked,proto3" json:"is_blocked,omitempty"`              // Go: bool
	Amounts       []*CurrencyAmount      `protobuf:"bytes,3,rep,name=amounts,proto3" json:"amounts,omitempty"`                                    // Go: []CurrencyAmount
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountBalance) Reset() {
	*x = AccountBalance{}
	mi := &file_acc_balance_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountBalance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountBalance) ProtoMessage() {}

func (x *AccountBalance) ProtoReflect() protoreflect.Message {
	mi := &file_acc_balance_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountBalance.ProtoReflect.Descriptor instead.
func (*AccountBalance) Descriptor() ([]byte, []int) {
	return file_acc_balance_proto_rawDescGZIP(), []int{0}
}

func (x *AccountBalance) GetAccountIdHash() []byte {
	if x != nil {
		return x.AccountIdHash
	}
	return nil
}

func (x *AccountBalance) GetIsBlocked() bool {
	if x != nil {
		return x.IsBlocked
	}
	return false
}

func (x *AccountBalance) GetAmounts() []*CurrencyAmount {
	if x != nil {
		return x.Amounts
	}
	return nil
}

// описание типа CurrencyAmount
type CurrencyAmount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`     // Go: int64
	Decimals      int32                  `protobuf:"varint,2,opt,name=decimals,proto3" json:"decimals,omitempty"` // Go: int32 (int8 не определён спецификацией proto3)
	Symbol        string                 `protobuf:"bytes,3,opt,name=symbol,proto3" json:"symbol,omitempty"`      // Go: string
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CurrencyAmount) Reset() {
	*x = CurrencyAmount{}
	mi := &file_acc_balance_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CurrencyAmount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CurrencyAmount) ProtoMessage() {}

func (x *CurrencyAmount) ProtoReflect() protoreflect.Message {
	mi := &file_acc_balance_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CurrencyAmount.ProtoReflect.Descriptor instead.
func (*CurrencyAmount) Descriptor() ([]byte, []int) {
	return file_acc_balance_proto_rawDescGZIP(), []int{1}
}

func (x *CurrencyAmount) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *CurrencyAmount) GetDecimals() int32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *CurrencyAmount) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

var File_acc_balance_proto protoreflect.FileDescriptor

const file_acc_balance_proto_rawDesc = "" +
	"\n" +
	"\x11acc_balance.proto\x12\x0faccount.v1beta1\"\x92\x01\n" +
	"\x0eAccountBalance\x12&\n" +
	"\x0faccount_id_hash\x18\x01 \x01(\fR\raccountIdHash\x12\x1d\n" +
	"\n" +
	"is_blocked\x18\x02 \x01(\bR\tisBlocked\x129\n" +
	"\aamounts\x18\x03 \x03(\v2\x1f.account.v1beta1.CurrencyAmountR\aamounts\"\\\n" +
	"\x0eCurrencyAmount\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bdecimals\x18\x02 \x01(\x05R\bdecimals\x12\x16\n" +
	"\x06symbol\x18\x03 \x01(\tR\x06symbolB\bZ\x06./mainb\x06proto3"

var (
	file_acc_balance_proto_rawDescOnce sync.Once
	file_acc_balance_proto_rawDescData []byte
)

func file_acc_balance_proto_rawDescGZIP() []byte {
	file_acc_balance_proto_rawDescOnce.Do(func() {
		file_acc_balance_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_acc_balance_proto_rawDesc), len(file_acc_balance_proto_rawDesc)))
	})
	return file_acc_balance_proto_rawDescData
}

var file_acc_balance_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_acc_balance_proto_goTypes = []any{
	(*AccountBalance)(nil), // 0: account.v1beta1.AccountBalance
	(*CurrencyAmount)(nil), // 1: account.v1beta1.CurrencyAmount
}
var file_acc_balance_proto_depIdxs = []int32{
	1, // 0: account.v1beta1.AccountBalance.amounts:type_name -> account.v1beta1.CurrencyAmount
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_acc_balance_proto_init() }
func file_acc_balance_proto_init() {
	if File_acc_balance_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_acc_balance_proto_rawDesc), len(file_acc_balance_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_acc_balance_proto_goTypes,
		DependencyIndexes: file_acc_balance_proto_depIdxs,
		MessageInfos:      file_acc_balance_proto_msgTypes,
	}.Build()
	File_acc_balance_proto = out.File
	file_acc_balance_proto_goTypes = nil
	file_acc_balance_proto_depIdxs = nil
}
